### ISSUE TITLE
Error : scroll top 

### ISSUE THREAD

**Issue by daghfous** [dflourusso/v-infinite-scroll#1]
When scrolling to the top, it scrolls automatically downwards while it must stay at the level of the last loaded message.

**Comment by dflourusso** [comment]
Are you using the _Normal Scroll_ or _Bidirectional Scroll_ [See the demo](https://dflourusso.github.io/v-infinite-scroll/)

I did not understand your problem, could you provide more information?

**Comment by daghfous** [comment]
when i scroll to the top, i want to prevent automatic scroll after loading more data
PS : i'm using the Bidirectional Scroll

**Comment by dflourusso** [comment]
It isn't an error or bug, it's a behavior.

Added a prop called `onTopScrollsToBottom`. You can pass `false` to disable the automatically scroll.

Update to version **1.0.4**

See [THIS](https://github.com/dflourusso/v-infinite-scroll#properties) docs
